parts/parts/urls.py
# Main urls.py

from django.contrib import admin
from django.urls import re_path, path, include

from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('', include('catalog.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('verification/', include('verify_email.urls')),
    path('tracking/', include('tracking.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += [re_path(r'[.]*', views.redirect_url, name="redirect-url")]

parts/users/urls.py
# Users views.py

from django.urls import path, include

from .forms import UserPasswordChangeForm, UserPasswordResetForm
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', views.loginPage, name="login-page"),
    path('logout/', views.logoutPage, name="logout-page"),
    path('register/', views.registerPage, name="register-page"),
    path('profile/', views.userPage, name='user-page-redirect'),
    path('profile/<str:user_name>/', views.userPage, name="profile-page"),
    path('naughty-user/', views.naughty_user, name='naughty-page'),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="base/password-reset.html", html_email_template_name='base/password-reset-email.html', form_class=UserPasswordResetForm), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="base/password-reset-done.html"), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="base/password-reset-form.html", form_class=UserPasswordChangeForm), name='password_reset_confirm'),
    path('password-reset-complete/', views.passwordComplete, name='password_reset_complete'),
    path('reset-username-check/', views.resetUsernameCheck, name='reset-username-check'),

    path('contact-us/', views.contact_admin, name='contact-us'),
    path('active-contact-submissions/<str:msg_type>/', views.active_contact_submissions, name='active-contact-submissions'),
    path('active-contact-review/<int:contact_id>/', views.active_contact_review, name='active-contact-review'),


]

parts/users/models.py
#Users models.py

from django.db import models
from django.contrib.auth.models import User

class ContactUs(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField(blank=False)
    message_type = models.CharField(max_length=20, choices=(("general", "General"), ("bug", "Bug"), ("suggestion", "Suggestion")))
    reviewed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def snippet(self):
        return self.message[:50] + "..."

parts/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django import forms
from .models import ContactUs

from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm

class UserLogin(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UserLogin, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Username...'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Password...'})

class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class' : 'form-control', "placeholder" : "Username...", "required" : "required"})
        self.fields['first_name'].widget.attrs.update({'class' : 'form-control', "placeholder" : "First Name...", "required" : "required"})
        self.fields['last_name'].widget.attrs.update({'class' : 'form-control', "placeholder" : "Last Name...", "required" : "required"})
        self.fields['email'].widget.attrs.update({'class' : 'form-control', "placeholder" : "Email...", "required" : "required"})
        self.fields['password1'].widget.attrs.update({'class' : 'form-control', "placeholder" : "Password...", "required" : "required"})
        self.fields['password2'].widget.attrs.update({'class' : 'form-control', "placeholder" : "Confirm Password...", "required" : "required"})

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.password = make_password(self.cleaned_data["password1"])
        user.username = self.cleaned_data["username"]
        user.username = user.username.lower()
        if commit:
            user.save()
        return user

class UsernameVerification(forms.Form):
    username = forms.CharField(required=True, max_length=100)

    def __init__(self, *args, **kwargs):
        super(UsernameVerification, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class' : 'form-control', "name": "username", "placeholder" : "Username...", "required" : "required"})

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            return username
        else:
            raise forms.ValidationError("Username does not exist")

class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'label' : '', 'class' : 'form-control', "placeholder" : "Email...", "required" : "required"})

class UserPasswordChangeForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs.update({'class' : 'form-control', "placeholder" : "New Password...", "required" : "required"})
        self.fields['new_password2'].widget.attrs.update({'class' : 'form-control', "placeholder" : "Confirm New Password...", "required" : "required"})


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ('message',)
        widgets = {
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': '5', 'placeholder': 'Message...'})
        }
    
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Message...'})

        
    def save(self, commit=True, message_type="general", created_by=None):
        contact = super(ContactForm, self).save(commit=False)
        contact.created_by = created_by
        contact.message_type = message_type
        if commit:
            contact.save()
        return contact

parts/users/views.py
# Users views.py


from django.shortcuts import render, redirect
from .forms import *
from .models import ContactUs
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .decorators import unauthenticated_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from verify_email.email_handler import send_verification_email
from catalog.views import is_member
from datetime import timedelta
from django.utils import timezone

# Create your views here.
@login_required(login_url='login/')
def userPage (request, user_name=None):

    if not is_member(request.user, "admin"):
        return render(request, 'base/user-page-notice.html', {})
    
    if user_name == None:
        user = request.user
        return redirect('profile-page', user_name=user.username)
    else:
        try:
            user = User.objects.get(username=user_name)
            if user.username.lower() == request.user.username.lower():
                msg = "You are viewing your own profile"
                return render(request, "base/user.html", {"passed_string": msg})
            else:
                msg = "You are viewing " + user.username + "'s profile"
                return render(request, 'base/user.html', {"passed_string": msg})
        except User.DoesNotExist:
            msg = f"Profile not found for {user_name}"
            return render(request, 'base/user.html', {"passed_string": msg})

    return render(request, 'base/user.html', {"user": user, "user_name": user_name})

@unauthenticated_user
def loginPage (request):
    form = UserLogin()
    if request.method == "POST":
        form = UserLogin(request.POST)
        username = request.POST.get('username')
        username = username.lower()
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            try:
                next_page = request.POST.get('next')
                if next_page:
                    return redirect(next_page)
                else:
                    return redirect('home')
            except KeyError:
                return redirect('home')
            
        else:
            messages.error(request, "Username or password is incorrect")

    return render(request, 'base/login.html', {"form": form})

@login_required(login_url='login-page')
def logoutPage (request):
    logout(request)
    return redirect('home')

def naughty_user(request):
    return render(request, 'base/naughty.html', {})

@unauthenticated_user
def registerPage (request):
    
    form = CreateUserForm()

    if request.method == "POST":
        # return redirect('naughty-page')
        
        form = CreateUserForm(request.POST)
        username = request.POST.get('username')
        username = username.lower()
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')

        if form.is_valid():
            
            try:
                username = form.cleaned_data['username']
                _ = User.objects.get(username=username)
                messages.error(request, f"Username {username} already exists")
                return render(request, 'base/register.html', {"form": form})
            except:
                inactive_user = send_verification_email(request, form)
                # user = User.objects.get(username=username)
                # user.username = username
                # user.save()
                # print(user)
                messages.success(request, "Please check your email for verification to login")
            return redirect('login-page')

        else:
            if username:
                try:
                    _ = User.objects.get(username=username)
                    messages.error(request, "Username already exists")
                    return render(request, 'base/register.html', {"form": form})
                except:
                    pass
            if email:
                try:
                    _ = User.objects.get(email=request.POST.get('email'))
                    messages.error(request, "Email already in system. Login instead")
                    return redirect('login-page')
                except:
                    pass
            
            if form.cleaned_data.get('password1') != form.cleaned_data.get('password2'):
                messages.error(request, "Passwords do not match")
                return render(request, 'base/register.html', {"form": form})

            messages.error(request, "Invalid form")


    return render(request, 'base/register.html', {"form": form})

def resetUsernameCheck(request):
    
    form = UsernameVerification()

    if request.method == "POST":
        
        form = UsernameVerification(request.POST)
        if form.is_valid():

            username = form.clean_username()


            try:
                user = User.objects.get(username=username)
                
                uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
                token = default_token_generator.make_token(user)
                # return redirect('password_reset', uidb64=uidb64, token=token)
                return redirect('password_reset')
            except Exception as e:
                print(e)
                messages.error(request, "Username not found")
        else:
            messages.error(request, "Invalid form")
    
    return render(request, 'base/password-reset-username-check.html', {"form": form})


def passwordComplete(request):
    messages.success(request, "Password reset successful. Please login using your new credentials.")
    return redirect('login-page')


    # form page to be used for both issues and suggestions. Form results emailed to the admin.
@login_required(login_url='login-page')
def contact_admin(request):
    
    try:
        last_submission_time = ContactUs.objects.filter(created_by=request.user).order_by('-created_at').first().created_at
        allowed_time = timezone.now() - timedelta(seconds=30)
        if last_submission_time > allowed_time:
            difference = last_submission_time - allowed_time
            if difference > timedelta(seconds=1):
                msg = f"You have already submitted a message. Please wait {str(difference).split(':')[-1].split('.')[0]} more seconds before submitting another."
            else:
                msg = f"You have already submitted a message. Please wait {str(difference).split(':')[-1].split('.')[0]} more second before submitting another."

            messages.error(request, msg)
            return redirect('home')
    except:
        pass


    if request.method == "POST":

        form = ContactForm(request.POST)

        message = request.POST.get('message')
        if len(message) < 10:
            messages.error(request, "Message must be at least 10 characters")
            return render(request, "base/contact-admin.html", {'form': form})


        msg_type = request.POST.get("msg_type")
        if not msg_type:
            messages.error(request, "Please select a type of message to send")
            return render(request, "base/contact-admin.html", {'form': form})


        user = request.user

        form.created_by = user
        if form.is_valid():
            try:
                subject = msg_type.capitalize() + " - LaptopDB Contact Us Form Message"
                message = "From User: " + user.username + "\n" + "Name: " + user.first_name + " " + user.last_name + "\n" + "User Email: " + user.email + "\n" + "Joined: " + str(user.date_joined) + "\n\n" + form.cleaned_data['message']
                sender = settings.FROM_EMAIL
                recipients = [settings.FROM_EMAIL]
                send_mail(subject, message, sender, recipients)
                messages.success(request, f"{msg_type.capitalize()} submission successful.")
            except Exception as e:
                print(e)
                messages.error(request, f"Error sending message.")
                return render(request, "base/contact-admin.html", {'form': form})
            
            try:
                form.save(message_type=msg_type, created_by=user)
            except Exception as e:
                print(e)
            return redirect('home')
        else:
            print(form.errors)
            messages.error(request, f"Invalid Form.")
            return render(request, "base/contact-admin.html", {'form': form})
        
    else:
        form = ContactForm()
    return render(request, "base/contact-admin.html", {'form': form})

@login_required(login_url='login-page')
def active_contact_submissions(request, msg_type):
    
    if not is_member(request.user, "admin"):
        return redirect('home')

    title = msg_type.capitalize()

    submissions = ContactUs.objects.filter(message_type=msg_type).filter(reviewed=False)

    return render(request, "base/active-contact-submissions.html", {'submissions': submissions, 'title': title})

@login_required(login_url='login-page')
def active_contact_review(request, contact_id):
    if not is_member(request.user, "admin"):
        return redirect('home')
    
    submission = ContactUs.objects.get(id=contact_id)

    if request.method == "POST":
        if request.POST.get('option') == "reviewed":
            submission.reviewed = True
            submission.save()
            messages.success(request, f"{submission.message_type.capitalize()} submission marked as reviewed.")
            return redirect('active-contact-submissions', msg_type=submission.message_type)
        else:
            submission.reviewed = False

parts/users/templates/base/active-contact-review.html
{% extends 'main.html' %}

{% block content %}
<section class="suggest-model">
    <div class="container">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card model-change-card" style="border-radius: 1rem;">
                <div class="d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        <form method="POST" action=''>
                            {% csrf_token %}
                            <div class="d-flex align-items-center ml-0 mb-3 pb-1">
                                <span class="h1 fw-bold mb-0">Contact Submission Review</span>
                            </div>

                            <div class="form-outline mb-4 input-group">
                                <span class="input-group-text form-span" id="id_type">Submission Type</span>
                                <span class="form-control form-span" id="id_type_ans">{{submission.message_type}}</span>
                            </div>
                            <div class="form-outline mb-4 input-group">
                                <span class="input-group-text form-span" id="id_created_by">Submitted By</span>
                                <span class="form-control form-span" id="id_created_by_ans">{{submission.created_by}}</span>
                            </div>
                            <div class="form-outline mb-4 input-group">
                                <span class="input-group-text form-span" id="id_date">Submission Date</span>
                                <span class="form-control form-span" id="id_date_ans">{{submission.created_at}}</span>
                            </div>

                            <div class="form-outline mb-4 input-group">
                                <textarea class="form-control form-span" id="id_message" readonly>{{submission.message}}</textarea>
                            </div>

                            <button class="btn btn-success me-4" type="submit" name="option" value="reviewed">Reviewed</button>

                            <button class="btn btn-secondary" type="cancel" name="option" value="cancel">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

parts/users/templates/base/expired-verification.html
{% extends 'main.html' %}

{% block content %}
<section class="verification">
    <div class="container py-5 mx-auto">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card user-card" style="border-radius: 1rem;">
                <div class="d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        <span class="h1 fw-bold mb-3 mx-auto">{{status}}</span>
                        <p href="" class="small text-muted m-4">Link expired or cannot validate. Please request a new link below.</p>
                        <div class="form-outline mb-4">
                            <a href={% url 'request-new-link-from-token' encoded_email encoded_token %}><button class="btn btn-dark btn-block w-100">Re-send Link</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

parts/users/templates/base/login.html
{% extends 'main.html' %}

{% block content %}
<section class="login">
    <div class="container py-5 mx-auto">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card user-card" style="border-radius: 1rem;">
                <div class="d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}" />
                            <div class="d-flex align-items-center ml-0 mb-3 pb-1">
                                <span class="h1 fw-bold mb-0">LaptopDB</span>
                            </div>

                            <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>

                            <div class="form-outline mb-4">
                                {{form.username}}
                            </div>

                            <div class="form-outline mb-4">
                                {{form.password}}
                            </div>

                            <div class="form-outline mb-4">
                                <button class="btn btn-dark btn-block w-100" type="submit">Login</button>
                            </div>

                            <a class="small text-muted" href="{% url 'password_reset' %}">Forgot login info?</a>
                            <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{% url 'register-page' %}"
                                style="color: #393f81;">Register here</a></p>
                            {% comment %} <a href="#!" class="small text-muted">Terms of use.</a>
                            <a href="#!" class="small text-muted">Privacy policy</a> {% endcomment %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

parts/users/templates/base/new-email-sent.html
{% extends 'main.html' %}

{% block content %}
<section class="verification">
    <div class="container py-5 mx-auto">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card user-card" style="border-radius: 1rem;">
                <div class="d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        <span class="h1 fw-bold mb-3 mx-auto">Success</span>
                        <p href="" class="small text-muted m-4">New email has been sent. Please check your inbox and upon successful verification you will be able to login.</p>
                        <div class="form-outline mb-4">
                            <a href={% url 'login-page' %}><button class="btn btn-dark btn-block w-100">Login</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

parts/users/templates/base/password-reset-done.html
{% extends 'main.html' %}

{% block content %}
<section class="login">
    <div class="container py-5 mx-auto">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card user-card" style="border-radius: 1rem;">
                <div class="d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        <form method="" action="">

                            <div class="d-flex align-items-center ml-0 mb-3 pb-1">
                                <span class="h1 fw-bold mb-0">LaptopDB</span>
                            </div>

                            <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">If an account exists with that email, a reset link will be sent. Please allow up to a few minutes for delivery and be sure to check inbox as well as spam folders.</h5>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

parts/users/templates/base/password-reset-email.html
<html>
    {% load i18n %}{% autoescape off %}
    <p>{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at laptop-db.com.{% endblocktranslate %}</p>

    <p>{% translate "Please go to "%}<a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}">{% translate "this page "%}</a>{% translate "and choose a new password, or copy and paste the link below into your browser." %}</p>
    {% block reset_link %}
    <p>{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}</p>
    {% endblock %}
    <p>{% translate 'Your username, in case you’ve forgotten:' %} <strong>{{ user.get_username }}</strong></p>

    <p>{% translate 'If you did not request a password reset please ignore this message or contact us if you would like assistance.'%}</p>

    <p>{% blocktranslate %}The LaptopDB team{% endblocktranslate %}</p>

    {% endautoescape %}
</html>

parts/users/templates/base/password-reset-form.html
{% extends 'main.html' %}

{% block content %}
<section class="login">
    <div class="container py-5 mx-auto">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card user-card" style="border-radius: 1rem;">
                <div class="d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}" />
                            <div class="d-flex align-items-center ml-0 mb-3 pb-1">
                                <span class="h1 fw-bold mb-0">LaptopDB</span>
                            </div>

                            <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Create your new password</h5>

                            <div class="form-outline mb-4">
                                {{ form.new_password1 }}
                            </div>

                            <div class="form-outline mb-4">
                                {{ form.new_password2 }}
                            </div>

                            <div class="form-outline mb-4">
                                <button class="btn btn-dark btn-block w-100" type="submit">Change Password</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

parts/users/templates/base/password-reset.html
{% extends 'main.html' %}

{% block content %}
<section class="login">
    <div class="container py-5 mx-auto">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card user-card" style="border-radius: 1rem;">
                <div class="d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        <form method="POST" action="">
                            {% csrf_token %}
                            
                            <div class="d-flex align-items-center ml-0 mb-3 pb-1">
                                <span class="h1 fw-bold mb-0">LaptopDB</span>
                            </div>

                            <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Enter info below to reset password</h5>

                            <div class="form-outline mb-4">
                                {{form}}
                            </div> 

                            <div class="form-outline mb-4">
                                <button class="btn btn-dark btn-block w-100" type="submit">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

parts/users/templates/base/register.html
{% extends 'main.html' %}

{% block content %}
<section class="register">
    <div class="container py-5 mx-auto">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card user-card" style="border-radius: 1rem;">
                <div class="d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}" />
                            <div class="d-flex align-items-center ml-0 mb-3 pb-1">
                                <span class="h1 fw-bold mb-0">LaptopDB</span>
                            </div>

                            <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Registration opening soon</h5>

                            <div class="form-outline mb-4">
                                {{form.username}}
                            </div>

							<div class="form-outline mb-4">
                                {{form.first_name}}
                            </div>

							<div class="form-outline mb-4">
                                {{form.last_name}}
                            </div>

                            <div class="form-outline mb-4">
                                {{form.email}}
                            </div> 
                            
                            <div class="form-outline mb-4">
                                {{form.password1}}
                            </div>

                            <div class="form-outline mb-4">
                                {{form.password2}}
                            </div>

                            <div class="form-outline mb-4">
                                <button class="btn btn-dark btn-block w-100" type="submit">Register</button>
                                {% comment %} <input class="btn login_btn" type="submit" value="Login"> {% endcomment %}
                            </div>

                            {% comment %} <a class="small text-muted" href="#!">Forgot password?</a> {% endcomment %}
                            <p class="mb-5 pb-lg-2" style="color: #393f81;">Already have an account? <a href="{% url 'login-page' %}"
                                style="color: #393f81;">Login here</a></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}