parts/catalog/urls.py
# Catalog urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('search/', views.search_results, name='search-results'),
    path('add-laptop/', views.add_laptop, name='add-laptop'),
    path('edit-laptop/<str:laptop_model>/', views.edit_laptop, name='edit-laptop'),
    path('item/<str:model_number>/', views.item_page, name='item-page'),
    path('laptop/<str:laptop_model>/', views.laptop_page, name='laptop-page'),
    path('part-upvote/', views.part_upvote, name='part-upvote'),
    path('laptop-upvote/', views.laptop_upvote, name='laptop-upvote'),
    path('laptop-downvote/', views.laptop_downvote, name='laptop-downvote'),
    path('part-downvote/', views.part_downvote, name='part-downvote'),
    path('part-model-change/<str:part_model>', views.part_model_change, name='part-model-change'),
    path('laptop-model-change/<str:laptop_model>', views.laptop_model_change, name='laptop-model-change'),
    path('requested-part-changes', views.requested_part_changes, name='requested-part-changes'),
    path('requested-part-change-review/<int:part_model_change_id>', views.requested_part_change_review, name='requested-part-change-review'),
    path('requested-laptop-changes', views.requested_laptop_changes, name='requested-laptop-changes'),
    path('requested-laptop-change-review/<int:laptop_model_change_id>', views.requested_laptop_change_review, name='requested-laptop-change-review'),
    path('delete-laptop/<int:laptop_id>/', views.confirm_delete_laptop, name='confirm-delete-laptop'),
    path('delete-part/<int:part_id>/', views.confirm_delete_part, name='confirm-delete-part'),
    path('verify-part/<int:part_id>/', views.verify_part, name='verify-part'),
    path('verify-laptop/<int:laptop_id>/', views.verify_laptop, name='verify-laptop'),
]

parts/parts/urls.py
# Main urls.py

from django.contrib import admin
from django.urls import re_path, path, include

from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('', include('catalog.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('verification/', include('verify_email.urls')),
    path('tracking/', include('tracking.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += [re_path(r'[.]*', views.redirect_url, name="redirect-url")]

parts/catalog/models.py
# Catalog Models

from django.db import models, IntegrityError
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.core.exceptions import ValidationError
from django.core.validators import validate_image_file_extension

CATEGORY_CHOICES = (
('LCD', 'LCD'),
('KEYB', 'Keyboard'),
('BATT', 'Battery'),
('PALR', 'Palm Rest'),
('BOTC', 'Bottom Cover'),
('LCDB', 'LCD Bezel'),
('LCDC', 'LCD Cover'),
('LCDT', 'LCD Touch Assembly'),
('DICA', 'Display Cable'),
('LFTH', 'Left Hinge'),
('RAM', 'RAM'),
('RGTH', 'Right Hinge'),
('CHRP', 'Charging Port'),
('CPUF', 'CPU Fan'),
('SATC', 'SATA Cable/Flex'),
('SATS', 'SATA Sub Board'),
('POW', 'Power Button'),
('PBFC', 'Power Button Flex Cable'),
('HDDC', 'Hard Drive Caddy'),
('TRA', 'Track pad'),
('TPFC', 'Track pad Flex Cable'),
('SPE', 'Speakers'),
('CAM', 'Camera'),
('CHAR', 'Charger'),
('MIC', 'Microphone'),
('HEAT', 'Heat sink'),
('MOTH', 'Motherboard'),
('GRAC', 'Graphics Card'),
('WIFI', 'Wi-Fi Adapter'),
('WIFA', 'Wi-Fi Antenna'),
('CDD', 'CD Drive'),
('SB01', 'Sub Board 1'),
('SB02', 'Sub Board 2'),
('SB03', 'Sub Board 3'),
('SBC1', 'Sub Board Flex Cable 1'),
('SBC2', 'Sub Board Flex Cable 2'),
('SBC3', 'Sub Board Flex Cable 3')
)

# class Upload(models.Model):
#     uploaded_at = models.DateTimeField(auto_now_add=True)
#     file = models.FileField()

def validate_file_extension(value):
    import os
    ext = os.path.splitext(value.name)[-1]
    valid_extensions = ['.png', '.jpg', '.jpeg', '.gif'],
    valid = False
    if ext.lower() in valid_extensions:
        valid = True
    if not valid:
        raise ValidationError(u'File not supported!')


class Serial_Number(models.Model):
    serial_number = models.CharField(max_length=200, unique=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.serial_number

class Laptop(models.Model):
    laptop_model = models.CharField(max_length=200, unique=True, null=True)
    manufacturer = models.CharField(max_length=200, null=True, blank=True)
    series = models.CharField(max_length=200, null=True, blank=True)
    serial_number = models.ManyToManyField(Serial_Number, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    country_id = CountryField(blank_label='-- Optional -- Select Country -- ', null=True, blank=True)
    image = models.FileField(null=True, blank=True, validators=[validate_image_file_extension])
    score = models.IntegerField(default=0)
    verified = models.BooleanField(default=False)
    verified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='laptop_verification_approved_by')
    verified_date = models.DateTimeField(null=True, blank=True)
    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.laptop_model

    def upvote(self, user):
        try:
            self.laptopvote_set.create(user=user, laptop=self, vote_type=True)
            self.score += 1
            self.save()
        except IntegrityError:
            vote = self.laptopvote_set.filter(user=user)
            if vote[0].vote_type == False:
                vote.update(vote_type=True)
                self.score += 2
                self.save()
                return "Downvote switched to upvote"
            elif vote[0].vote_type == True:
                self.score -= 1
                self.save()
                vote.delete()
                return "Removed upvote"
            else:
                return "You have already voted"
        return "Vote successful"


    def downvote(self, user):
        try:
            self.laptopvote_set.create(user=user, laptop=self, vote_type=False)
            self.score -= 1
            self.save()
        except IntegrityError:
            vote = self.laptopvote_set.filter(user=user)
            if vote[0].vote_type == True:
                vote.update(vote_type=False)
                self.score -= 2
                self.save()
                return "Upvote switched to downvote"
            elif vote[0].vote_type == False:
                self.score += 1
                self.save()
                vote.delete()
                return "Removed downvote"
            else:
                return "You have already voted"
        return "Vote successful"
    

class Part(models.Model):
    model = models.CharField(max_length=200, null=True, blank=True, unique=True)
    laptop_model = models.ManyToManyField(Laptop)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    country_id = CountryField(blank_label='-- Select Country --', null=True, blank=True)
    part_type = models.CharField(choices=CATEGORY_CHOICES, max_length=4, null=True, blank=True)
    image = models.FileField(null=True, blank=True, validators=[validate_image_file_extension])
    score = models.IntegerField(default=0)
    verified = models.BooleanField(default=False)
    verified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='part_verification_approved_by')
    verified_date = models.DateTimeField(null=True, blank=True)
            
    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.model

    def upvote(self, user):
        try:
            self.partvote_set.create(user=user, part=self, vote_type=True)
            self.score += 1
            self.save()
        except IntegrityError:
            vote = self.partvote_set.filter(user=user)
            if vote[0].vote_type == False:
                vote.update(vote_type=True)
                self.score += 2
                self.save()
                return "Downvote switched to upvote"
            elif vote[0].vote_type == True:
                vote.update(vote_type=False)
                self.score -= 1
                self.save()
                vote.delete()
                return "Removed upvote"
            else:
                return "You have already voted"
        return "Upvote successful"

    def downvote(self, user):
        try:
            self.partvote_set.create(user=user, part=self, vote_type=False)
            self.score -= 1
            self.save()
        except IntegrityError:
            vote = self.partvote_set.filter(user=user)
            if vote[0].vote_type == True:
                vote.update(vote_type=False)
                self.score -= 2
                self.save()
                return "Upvote switched to downvote"
            elif vote[0].vote_type == False:
                self.score += 1
                self.save()
                vote.delete()
                return "Removed downvote"
            else:
                return "You have already voted"
        return "Downvote successful"

class PartVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    vote_type = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user', 'part')

class LaptopVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    laptop = models.ForeignKey(Laptop, on_delete=models.CASCADE)
    vote_type = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user', 'laptop')

# Model to store part_model changes for admins to review and approve
class PartModelChange(models.Model):
    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    old_model = models.CharField(max_length=200, null=True, blank=True)
    new_model = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='part_change_approved_by')
    approved_date = models.DateTimeField(null=True, blank=True)
    rejected_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='part_change_rejected_by')
    rejected_date = models.DateTimeField(null=True, blank=True)
    rejected_reason = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        ordering = ['-updated', '-created']

class LaptopModelChange(models.Model):
    laptop = models.ForeignKey(Laptop, on_delete=models.CASCADE)
    old_model = models.CharField(max_length=200, null=True, blank=True)
    new_model = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='laptop_change_approved_by')
    approved_date = models.DateTimeField(null=True, blank=True)
    rejected_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='laptop_change_rejected_by')
    rejected_date = models.DateTimeField(null=True, blank=True)
    rejected_reason = models.CharField(max_length=200, null=True, blank=True)

    class Meta:

parts/catalog/forms.py
from .models import *
from django.forms import ModelForm
from django.contrib.admin.widgets import AdminFileWidget
from django import forms


class LaptopForm(ModelForm):
    class Meta:
        model = Laptop
        exclude = ("created", "updated", "created_by",)
        widgets = {'serial_number': forms.TextInput(attrs={})}
    
    def __init__(self, *args, **kwargs):
        super(LaptopForm, self).__init__(*args, **kwargs)
        self.fields['laptop_model'].widget.attrs.update({'class' : 'form-control input-field', "placeholder" : "Required", "required" : "required"})
        self.fields['manufacturer'].widget.attrs.update({'class' : 'form-control input-field', "placeholder" : "Dell, Lenovo, HP, etc..."})
        self.fields['series'].widget.attrs.update({'class' : 'form-control input-field', "placeholder" : "XPS, Thinkpad, Envy, etc..."})
        self.fields['serial_number'].widget.attrs.update({'class' : 'form-control input-field', "placeholder" : "Optional"})
        

class PartForm(ModelForm):
    class Meta:
        model = Part
        fields = '__all__'
        exclude = ("created", "updated", "country_id", "created_by", "laptop_model",)
        widgets = {
            'image' : AdminFileWidget()
        }


        
class ModelChangeForm(forms.Form):
    current_model = forms.CharField(label="Current", max_length=100)
    suggested_model = forms.CharField(label="Suggested", max_length=100)

    def __init__(self, *args, **kwargs):
        super(ModelChangeForm, self).__init__(*args, **kwargs)
        self.fields['current_model'].widget.attrs.update({'class' : 'form-control', "disabled" : "disabled"})
        self.fields['suggested_model'].widget.attrs.update({'class' : 'form-control input-field', "placeholder" : "Required"})

parts/catalog/templates/base/add-data.html
{% extends 'main.html' %}

{% block content %}

{% load countries %}
{% get_countries as countries %}

<div class='add-data container'>
    <div class='mx-auto'>
            <form class="form" name="parts-form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group mb-2">
                    <span class="input-group-text" id="id_manufacturer">Manufacturer</span>
                    {{ form.manufacturer }}
                    {% comment %} <input type="text" class="form-control" name="manufacturer" id="id_manufacturer" placeholder="Dell, Lenovo, HP, etc..." Required> {% endcomment %}
                </div>
                <div class="input-group mb-2">
                    <span class="input-group-text" id="id_series">Series</span>
                    {{ form.series }}
                   
                    {% comment %} <input type="text" class="form-control" name="series" id="id_series" placeholder="XPS, Thinkpad, Envy, etc..." Required> {% endcomment %}
                </div>
                <div class="input-group mb-2">
                    <span class="input-group-text" id="id_laptop_model">Model Number</span>
                    {{ form.laptop_model }}
                   
                    {% comment %} <input type="text" class="form-control" name="laptop_model" id="id_laptop_model" placeholder="Required" Required> {% endcomment %}
                </div>
                <div class="input-group mb-2">
                    <span class="input-group-text" id="id_serial_number">Serial Number</span>
                    {{ form.serial_number }}

                    {% comment %} <input type="text" class="form-control" name="serial_number" id="id_serial_number" placeholder="Optional"> {% endcomment %}
                </div>
                <div class="input-group mb-2">
                    <span class="input-group-text" id="id_country_id">Country</span>
                    <select class="form-select" id="id_country_id" aria-label="Country select" data-live-search="true" placeholder="Test">
                        <option selected>Select Country -- Optional</option>
                        {% for country in countries %}
                            <option value="{{ country.code }}">{{ country.name }}</option>
                        {% endfor %}
                      </select>
                </div>

                <div class="input-group mb-2">
                    <input type="file" class="form-control" name="laptop-image" id="id_laptop-image">
                </div>
                <input class="btn btn-secondary" type="submit" value="Submit" />
            </form>
    </div>
</div>

{% endblock %}

parts/catalog/templates/base/add-laptop.html
{% extends 'main.html' %}

{% block content %}

{% load countries %}
{% get_countries as countries %}



<div class='add-data container'>
    <div class='mx-auto my-auto'>
            <form class="form" name="parts-form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}                
                <div class="input-group mb-2">
                    <span class="input-group-text form-span" id="id_manufacturer">Manufacturer</span>
                    {{ form.manufacturer }}
                    {% comment %} <input type="text" class="form-control" name="manufacturer" id="id_manufacturer" placeholder="Dell, Lenovo, HP, etc..." Required> {% endcomment %}
                </div>
                <div class="input-group mb-2">
                    <span class="input-group-text form-span" id="id_series">Series</span>
                    {{ form.series }}
                   
                    {% comment %} <input type="text" class="form-control" name="series" id="id_series" placeholder="XPS, Thinkpad, Envy, etc..." Required> {% endcomment %}
                </div>
                <div class="input-group mb-2">
                    <span class="input-group-text form-span" id="id_laptop_model">Model Number</span>
                    {{ form.laptop_model }}
                   
                    {% comment %} <input type="text" class="form-control" name="laptop_model" id="id_laptop_model" placeholder="Required" Required> {% endcomment %}
                </div>
                <div class="input-group mb-2">
                    <span class="input-group-text form-span" id="id_serial_number">Serial Number</span>
                    {{ form.serial_number }}

                    {% comment %} <input type="text" class="form-control" name="serial_number" id="id_serial_number" placeholder="Optional"> {% endcomment %}
                </div>
                <div class="input-group mb-2">
                    <span class="input-group-text form-span" id="id_country_id">Country</span>
                    <select class="form-select input-field" id="id_country_id" aria-label="Country select" data-live-search="true" placeholder="Test">
                        <option selected>Select Country -- Optional</option>
                        {% for country in countries %}
                            <option value="{{ country.code }}">{{ country.name }}</option>
                        {% endfor %}
                      </select>
                </div>

                <div class="input-group mb-0">
                    <label class="input-group-text" for="image-input">Image</label>
                    <input id="image-input" type="file" onchange="validateSize(this)" class="form-control input-group-file mx-0 px-0" name="laptop-image" id="id_laptop-image">
                </div>
                <div class="small text-muted mt-0 mb-2">
                    <span>Image must be of type .png, .jpg, .jpeg, or .gif and less than 10MiB</span>
                </div>
                <div class="form-outline mt-3">
                    <button class="btn btn-dark btn-block w-100" type="submit" id="submit-button">Submit</button>
                </div>
            </form>
    </div>
</div>

{% endblock %}

parts/catalog/templates/base/confirm-verify.html
{% extends 'main.html' %}

{% block content %}
<section class="suggest-model">
    <div class="container">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card model-change-card" style="border-radius: 1rem;">
                <div class="d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        <form method="POST" action="">
                            {% csrf_token %}

                            <div class="d-flex align-items-center ml-0 mb-3 pb-1">
                                <span class="h1 fw-bold mb-0">Verification Options</span>
                            </div>

                            {% if is_verified %}
                            <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Ensure proper measures were taken to determine if un-verification is appropropriate.</h5>
                            {% else %}
                            <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Ensure proper measures were taken to determine if verification is appropropriate.</h5>
                            {% endif %}

                            <div class="form-outline mb-4 input-group">
                                <span class="input-group-text form-span" id="id_type">
                                    {% if is_verified %}
                                        Type Unverifying
                                    {% else %}
                                        Type Verifying
                                    {% endif %}
                                </span>
                                <span class="form-control form-span" id="id_type_ans">{{type_to_verify}}</span>
                            </div>

                            <div class="form-outline mb-4 input-group">
                                <span class="input-group-text form-span" id="id_model">Model</span>
                                <span class="form-control form-span" id="id_type_ans">{{model_number}}</span>
                            </div>
                            {% if is_verified %}
                                <button class="btn btn-danger me-4" type="submit" name="option" value="unverify">Unverify</button>
                            {% else %}
                                <button class="btn btn-success me-4" type="submit" name="option" value="verify">Verify</button>
                            {% endif %}
                            <button class="btn btn-secondary" type="cancel" name="option" value="cancel">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

parts/catalog/templates/base/home.html
{% extends 'main.html' %}

{% block content %}
    <main>
        <div class='home'>
            <div class="container">

                {% include 'base/recent-data-component.html' %}

            </div>
        </div>
    </main>
{% endblock %}

parts/catalog/templates/base/new-model-suggest.html
{% extends 'main.html' %}

{% block content %}
<section class="suggest-model">
    <div class="container">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card model-change-card" style="border-radius: 1rem;">
                <div class="d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        <form method="POST" action="">
                            {% csrf_token %}

                            <div class="d-flex align-items-center ml-0 mb-3 pb-1">
                                <span class="h1 fw-bold mb-0">Model Change Suggestion</span>
                            </div>

                            <div class="form-outline mb-4 input-group">
                                <span class="input-group-text form-span" id="id_current_model">Current</span>
                                {{model_change_form.current_model}}
                            </div>

                            <div class="form-outline mb-4 input-group">
                                <span class="input-group-text form-span" id="id_suggested_model">Suggested</span>
                                {{model_change_form.suggested_model}}
                            </div>

                            <div class="form-outline mb-4">
                                <button class="btn btn-dark btn-block w-100" type="submit">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

parts/catalog/templates/base/requested-laptop-change-review.html
{% extends 'main.html' %}

{% block content %}
<section class="suggest-model">
    <div class="container">
        <div class="container-flex-row justify-content-center align-items-center h-100">
            <div class="text-center mx-auto m-5">
                <span class="h1 fw-bold">Change Review for Laptop - {{laptop.old_model}}</span>
            </div>
            <div class="card model-change-card mx-auto p-0 mb-1" style="border-radius: 1rem;">
                <div class="card-body text-black">
                    <form method="POST" action=''>
                        {% csrf_token %}
                        <div class="form-outline input-group mb-2">
                            <span class="input-group-text" id="id_current_model">Current Model</span>
                            <span class="form-control" id="id_current_model" readonly>{{laptop.old_model}}</span>
                        </div>
                        <div class="form-outline input-group mb-2">
                            <span class="input-group-text" id="id_suggested_model">New Model</span>
                            <span class="form-control" id="id_suggested_model" readonly>{{laptop.new_model}}</span>
                        </div>
                        <div class="form-outline input-group mb-2">
                            <span class="input-group-text" id="id_suggested_by">Suggested By</span>
                            <span class="form-control" id="id_suggested_by" readonly>{{laptop.created_by}}</span>
                        </div>
                        <div class="btn-group form-outline input-group mb-2" role="group" aria-label="Approve or Reject toggle button group">
                            <input type="radio" class="btn-check" name="option" value="approved" id="id_approve" autocomplete="off">
                            <label class="btn btn-outline-grey approve" for="id_approve">Approve</label>
                          
                            <input type="radio" class="btn-check" name="option" value="rejected" id="id_reject" autocomplete="off">
                            <label class="btn btn-outline-grey reject" for="id_reject" >Reject</label>
                          </div>
                        <div class="form-outline input-group mb-2">
                            <span class="input-group-text">Reason</span>
                            <input type="text" class="form-control" placeholder="Approval or Rejection Reason..." id="id_reason" name="reason" aria-label="Reason for approval or rejection">
                        </div>
                        <div class="form-outline mt-4">
                            <button class="btn btn-dark btn-block w-100" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

parts/catalog/templates/base/requested-laptop-changes.html
{% extends 'main.html' %}

{% block content %}
<section class="suggest-model">
    <div class="container">
        <div class="container-flex-row justify-content-center align-items-center h-100">
            <div class="text-center mx-auto m-5">
                <span class="h1 fw-bold">Active Laptop Model Change Requests</span>
            </div>
            {% for laptop in laptops %}
            <div class="card suggested-change-card mx-auto p-0 mb-1" style="border-radius: 1rem;">
                <div class="card-body text-black">
                    <form>
                        <div class="form-outline input-group">
                        <a class="text-decoration-none form-outline input-group" href="{% url 'requested-laptop-change-review' laptop.id %}">
                            <span class="input-group-text" id="id_current_model">Laptop</span>
                            <span class="form-control me-3" id="id_current_model">{{laptop.old_model}}</span>
                            <span class="input-group-text" id="id_suggested_model">Suggested</span>
                            <span class="form-control me-3" id="id_suggested_model">{{laptop.new_model}}</span>
                            <span class="input-group-text" id="id_submitted_by">Submitted By</span>
                            <span class="form-control me-3" id="id_submitted_by">{{laptop.created_by}}</span>
                            <span class="input-group-text" id="id_submitted_date">Submitted Date</span>
                            <span class="form-control me-3" id="id_submitted_date">{{laptop.created}}</span>
                        </a>
                        </div>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

parts/catalog/templates/base/requested-part-changes.html
{% extends 'main.html' %}

{% block content %}
<section class="suggest-model">
    <div class="container">
        <div class="container-flex-row justify-content-center align-items-center h-100">
            <div class="text-center mx-auto m-5">
                <span class="h1 fw-bold">Active Part Model Change Requests</span>
            </div>
            {% for part, part_type in parts_data %}
            <div class="card suggested-change-card mx-auto p-0 mb-1" style="border-radius: 1rem;">
                <div class="card-body text-black">
                    <form>
                        <div class="form-outline input-group">
                        <a class="text-decoration-none form-outline input-group" href="{% url 'requested-part-change-review' part.id %}">
                            <span class="input-group-text" id="id_current_model">{{part_type}}</span>
                            <span class="form-control me-3" id="id_current_model">{{part.old_model}}</span>
                            <span class="input-group-text" id="id_current_model">Suggested</span>
                            <span class="form-control me-3" id="id_current_model">{{part.new_model}}</span>
                            <span class="input-group-text" id="id_submitted_by">Submitted By</span>
                            <span class="form-control me-3" id="id_submitted_by">{{part.created_by}}</span>
                            <span class="input-group-text" id="id_submitted_date">Submitted Date</span>
                            <span class="form-control me-3" id="id_submitted_date">{{part.created}}</span>
                        </a>
                        </div>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}